name: Run Algolia Scraper

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: "1BEGBIP9SH"
          algolia_api_key: "9d8e6ed4db04716282b15a926825fdcc"
          file: "docs/algolia.config.json"
